version: '3.3'

networks:
  core:
    driver: bridge
  udata: {}

volumes:
  udata-fs: {}
  mongo-data: {}
  redis-data: {}
  minio-data: {}
  elasticsearch-data: {}

services:
  mongo:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
    networks:
      - udata
      - core
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    networks:
      - core
    ports:
      - 8081:8081

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-data:/data
    networks:
      - udata
      - core
    ports:
      - 6379:6379

  arena:
    image: odlevakp/arena:2.4.2
    depends_on:
      - redis
    networks:
      - core
    volumes:
      - ./config/arena/queues.json:/opt/arena/src/server/config/index.json
    ports:
      - 4567:4567

  minio:
    image: minio/minio:RELEASE.2018-11-30T03-56-59Z
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - core
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio-s3cr3t
    ports:
      - 9000:9000

  udata:
    image: udata/udata:1.6
    networks:
      - udata
      - core
    volumes:
      - udata-fs:/udata/fs
      - ./config/udata/udata.cfg:/udata/udata.cfg
    environment:
      AUTHLIB_INSECURE_TRANSPORT: 1
    ports:
      - "7000:7000"

  elasticsearch:
    image: udata/elasticsearch
    networks:
      - udata
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
